version: "3"
services:
  db:
    container_name: ikura_db
    image: postgres:15-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'ikura'
      POSTGRES_DB: 'ikura'
      POSTGRES_PASSWORD: 'ikura'
    volumes:
      - ikura-db:/var/lib/postgresql/data

volumes:
  ikura-db:
