version: "3"
services:
  ikura-app:
    container_name: ikura_app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PW: 'ikura'
      HOST: 'db'
    ports:
      - '5000:5000'
    depends_on:
      - db
  db:
    container_name: ikura_db
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: 'ikura'
      POSTGRES_DB: 'ikura'
      POSTGRES_PASSWORD: 'ikura'
    volumes:
      - ikura-db:/var/lib/postgresql/data
volumes:
  ikura-db:
