name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Build the Docker image
  #     run: docker build . --file Dockerfile --tag ikura:$(date +%s)
  test_services:
    runs-on: ubuntu-latest
    # needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Start Docker Compose
      run: docker-compose up -d

    - name: Wait for services to be ready
      run: sleep 10

    - name: Run tests with curl
      run: |
        response_code=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:5000/test)
        echo "Response code: $response_code"
        if [ "$response_code" -eq 200 ]; then
          echo "Tests passed!"
        else
          echo "Tests failed!"
          exit 1
        fi

    - name: Stop Docker Compose
      run: docker-compose down -v
