name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test_services:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Start Docker Compose
      run: docker-compose up -d

    - name: Wait for services
      run: sleep 20

    - name: Test server is running and connected to db
      run: |
        retries=0
        until [ $retries -ge 10 ]; do
          response_code=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:5000)
          if [ "$response_code" -eq 200 ]; then
            echo "Flask app is ready!"
            break
          else
            echo "Waiting for Flask app to be ready..."
            retries=$((retries+1))
            sleep 10
          fi
        done

    # - name: Run tests with curl
    #   run: 
    - name: Stop Docker Compose
      run: docker-compose down -v
