name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test_services:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Start Docker Compose
      run: docker-compose up -d

    - name: Debug - Show Docker Compose logs
      run: docker-compose logs
      
    - name: Run DB Tests
      run: docker exec ikura_app python app_test.py
 
    - name: Stop Docker Compose
      run: docker-compose down -v
