name: Docker Compose CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'app/**'
      - 'Dockerfile'
  pull_request:
    paths:
      - 'app/**'
      - 'Dockerfile'

jobs:
  test_services:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Start Docker Compose
      run: docker-compose up -d
      
    - name: Check logs for server running
      run: docker-compose logs
      
    - name: Run Tests
      id: test
      run: |
        result=$(docker exec ikura_app python3 app_test.py)
        echo "result=$result" >> $GITHUB_OUTPUT

    - name: Check test results
      run: |
        if [[ "${{ steps.test.outputs.result }}" == *"Tests Passed"* ]]; then
          echo "Tests passed!"
        else
          echo "Tests failed!"
          exit 1
        fi
 
    - name: Tear down services
      run: docker-compose down -v
