name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'ikura-app/**'
  pull_request:
    paths:
      - 'ikura-app/**'
  workflow_dispatch:
    inputs:
      push-image:
        type: boolean
        description: 'Push Docker image to registry'
        default: false  # Default value is false for non-manual triggers

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v1.5.0
        with:
          dockerfile: ./ikura-app/Dockerfile

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWD }}

      - name: Get SHORT SHA commit
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build Docker image
        id: build-image
        run: |
          docker build -t ${{ secrets.DOCKER_USER }}/ikura:${{ env.SHORT_SHA }} ./ikura-app

      - name: Scan for vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'image'
          image-ref: '${{ secrets.DOCKER_USER }}/ikura:${{ env.SHORT_SHA }}'

      - name: Push Docker image
        if: ${{ github.event.inputs.push-image == true }}
        run: docker push ${{ secrets.DOCKER_USER }}/ikura:${{ env.SHORT_SHA }}
