name: build and push docker images
on:
   workflow_dispatch:
   push:
     branches:
     - main
     paths:
     - 'app/**'
     - 'Dockerfile'
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: set image tag
      run: |
        tag=$(git rev-parse --short ${{ github.sha }})
        echo "IMAGE_TAG=$tag" >> $GITHUB_ENV
        make get_sha

    # - name: Confirm git commit SHA output
    #   run: make get_sha

    - name: Build docker image
      run: make build
      
    - name: Push image
      run: make push
      env:
        USER: ${{ secrets.docker-user }}
        PASSWORD: ${{ secrets.docker-passwd }}
