name: build and push docker images
on:
   workflow_dispatch:
   pull_request:
    paths:
      - 'app/**'
      - 'Dockerfile'
      - 'Makefile'
   push:
     branches:
     - main
     paths:
     - 'app/**'
     - 'Dockerfile'
     - 'Makefile'
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: set image tag
      run: |
        tag=$(git rev-parse --short ${{ github.sha }})
        echo "IMAGE_TAG=$tag" >> $GITHUB_ENV
        make get_sha

    - name: Build docker image
      run: make build
      
    - name: Push image
      run: make push
      env:
        USER: ${{ secrets.DOCKER_USER }}
        PASSWORD: ${{ secrets.DOCKER_PASSWD }}

    - name: add comment on the image tag
      uses: mshick/add-pr-comment@v2.8.1
      with:
        message: "latest uploaded image tag is ${{ env.IMAGE_TAG }}"
        repo-token: ${{ secrets.GH_TOKEN }}
    