name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v1.5.0
        with:
          dockerfile: ./Dockerfile
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./ikura-app
          push: true
          tags: ${{ secrets.DOCKER_USER }}/ikura:${{ github.sha }}

      - name: Scan for vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'image'
          image-ref: 'docker.io/${{ secrets.DOCKER_USER }}/ikura:${{ github.sha }}'